version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test BencodeLib.Test\BencodeLib.Test.csproj
    xunit.console.clr4 Z1Torrent.Test\bin\Debug\Z1Torrent.Test.dll /appveyor